import { CommitsFetcher } from "components/CommitsFetcher";
import { Layout } from "components/Layout";
import Head from "next/head";
import { FC, useEffect, useState } from "react";

const CSR: FC = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);
  return (
    <Layout>
      <Head>
        <title>CSR example with Client-side loading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mounted && <CommitsFetcher />}
    </Layout>
  );
};

export default CSR;
