import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { FC } from 'react';
import { createOctoClient } from 'services/createOctoClient';
import { Commit, fetchCommits } from 'services/fetchCommits';
import styles from '../styles/Home.module.css';

export const getStaticProps: GetStaticProps<{
  commits: Array<Commit>;
}> = async () => {
  const client = createOctoClient();
  const commits = await fetchCommits(client);
  return {
    props: { commits },
    revalidate: 60, // In seconds
  };
};

const Home: FC<InferGetStaticPropsType<typeof getStaticProps>> = ({
  commits,
}) => {
  console.log(commits);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <h1 className={styles.title}>There are {commits.length} commits</h1>
        <div className={styles.grid}>
          {commits.map((commit) => (
            <a
              className={styles.card}
              key={commit.url}
              href={commit.url}
              target="_blank"
            >
              <p>{commit.message}</p>
              <small>
                <time dateTime={commit.author.date}>
                  {new Date(commit.author.date).toDateString()}
                </time>{' '}
                by {commit.author.name ?? 'Anonym'}
              </small>
            </a>
          ))}
        </div>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
